from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional
from app.brokers.base import BaseBroker
from app.services.data_feed import DataFeedService
from app.schemas.broker import OrderRequest, OrderResponse, Position
from loguru import logger


class SignalType(Enum):
    """Types of trading signals."""
    BUY = "buy"
    SELL = "sell"
    EXIT = "exit"
    HOLD = "hold"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    signal_type: SignalType
    symbol: str
    price: float
    timestamp: datetime
    strength: float = 1.0  # Signal strength 0-1
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def __repr__(self):
        return f"Signal({self.signal_type.value}, {self.symbol}, {self.price:.2f}, {self.timestamp})"


class BaseStrategy(ABC):
    """
    Abstract Base Class for all Trading Strategies.
    """
    def __init__(self, broker: BaseBroker, data_feed: DataFeedService, config: Dict[str, Any]):
        self.broker = broker
        self.data_feed = data_feed
        self.config = config
        self.positions: Dict[str, Position] = {}
        self.is_running = False

    async def start(self):
        """Called when strategy is started."""
        self.is_running = True
        logger.info(f"Strategy {self.__class__.__name__} started.")
        await self.on_start()

    async def stop(self):
        """Called when strategy is stopped."""
        self.is_running = False
        logger.info(f"Strategy {self.__class__.__name__} stopped.")
        await self.on_stop()

    @abstractmethod
    async def on_start(self):
        """Lifecycle hook: Strategy startup."""
        pass

    @abstractmethod
    async def on_stop(self):
        """Lifecycle hook: Strategy shutdown."""
        pass

    @abstractmethod
    async def on_tick(self, tick: Any):
        """Event hook: New tick data."""
        pass

    @abstractmethod
    async def on_candle(self, candle: Any):
        """Event hook: New candle (OHLC) data."""
        pass

    @abstractmethod
    async def on_order_update(self, order: OrderResponse):
        """Event hook: Order status update."""
        pass

    async def buy(self, symbol: str, quantity: int, price: Optional[float] = None, order_type: str = "MARKET"):
        """Helper to place BUY order."""
        # Implementation would construct OrderRequest and call self.broker.place_order
        pass

    async def sell(self, symbol: str, quantity: int, price: Optional[float] = None, order_type: str = "MARKET"):
        """Helper to place SELL order."""
        pass
